- ['Med-Flamingo', Null, 'MedFlamingo', 'Medical Foundation VLM (MedFlamingo)']
- ['LLaVA-Med', Null, 'LLaVA-Med', 'Medical Foundation VLM (LLaVA-Med)']
# - ['BioMedCLIP', Null, 'BioMedCLIP', 'Medical Foundation VLM (BioMedCLIP)']
