defaults:
  - _self_

retina_metadata_dir: 
retina_referral_metadata_dir: 

retina_halfmedian_image_dir: 
retina_median_image_dir: 

retina_referral_halfmedian_image_dir: 
retina_referral_median_image_dir: 

images_for_figures_dir: 

openai_api_key: 

pretrained_model_dir: 
flamingo_repo_dir: 
llava_med_repo_dir: 
llava_med_model_path: 
retfound_repo_dir: 
flamingo_llama_path: 
octlatent_repo_dir: 

llama3_path: 
wizardlm_path: 
vision_encoder_halfmedian_checkpoint: 
vision_encoder_5layer_checkpoint: 
vision_encoder_median_checkpoint: 

specialist_reports: 
tabular_variables: 
tabular_biomarker_variables: 

qa_output_dir: 

senior_ophthalmologist_evaluations: 
manual_predictions_path: 

hf_write_token: 
